//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT()
        {
            this.TICKETs = new HashSet<TICKET>();
        }
    
        public int STUDENTID { get; set; }
        public string STUDENTCODE { get; set; }
        public string STUDENTNAME { get; set; }
        public int CLASSID { get; set; }
        public Nullable<System.DateTime> LASTMODIFICATION { get; set; }
        public int PARENTID { get; set; }
    
        public virtual CLASS CLASS { get; set; }
        public virtual PARENT PARENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET> TICKETs { get; set; }
    }
}
