//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        public int TICKETID { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CONTENT { get; set; }
        public int ACTIONID { get; set; }
        public int STUDENTID { get; set; }
    
        public virtual ACTION ACTION { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
